{% set name = "cosmosis" %}
{% set version = "3.13.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 93a313ad20a8c7814d4cb87f1964199de8d5b34852e1885fb803324a68cb402a

build:
  number: 1
  # There is a problem with Linux OpenMPI that I would just like to skip for now
  skip: true  # [( (py < 36) or win ) or ( (mpi == "openmpi") and linux )]
  # OpenMPI fails to cross-compile to arm64 unless this variable is exported
  script: export OMPI_FC=${FC} && {{ PYTHON }} -m pip install . -vv


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
    - {{ compiler('cxx') }}
    - make
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    # needed for cross-compilation
    - {{ mpi }}                              # [build_platform != target_platform and mpi == "openmpi"]
  host:
    - python
    - pip
    - wheel
    - {{ mpi }}
    # needed to force the right pinnings
    # see https://github.com/conda-forge/conda-smithy/issues/1600
    - mpich ==3.*          # [mpi == "mpich ==3.*"]
    - mpich ==4.*          # [mpi == "mpich ==4.*"]
    - openmpi             # [mpi == "openmpi"]
    - liblapack
    - libblas
    - minuit2_standalone
    - setuptools
  run:
    # core
    - python
    - mpi4py
    - matplotlib-base
    - future
    - numpy
    - pip
    - pybind11
    - pyyaml
    # CSL has updates for this but need to check
    - scipy
    - setuptools
    - threadpoolctl
    - git
    # for samplers
    - emcee
    - dynesty
    - minuit2_standalone
    - zeus-mcmc
    - dulwich
    - nautilus-sampler >=1.0.1
    - astropy-base
    - getdist
    - pybobyqa

test:
  imports:
    - cosmosis
  commands:
    - test -f ${SP_DIR}/cosmosis/samplers/multinest/multinest_src/libnest3.so
    - test -f ${SP_DIR}/cosmosis/samplers/multinest/multinest_src/libnest3_mpi.so
    - test -f ${SP_DIR}/cosmosis/samplers/polychord/polychord_src/libchord.so
    - test -f ${SP_DIR}/cosmosis/samplers/polychord/polychord_src/libchord_mpi.so
    - mpirun -n 2 hostname
    - source cosmosis-configure && pytest --pyargs cosmosis
  requires:
    - pytest

about:
  home: https://github.com/joezuntz/cosmosis
  license: BSD-2-Clause AND LicenseRef-non-commerical-use-only
  license_family: BSD
  license_file:
    - LICENSE
    - cosmosis/samplers/multinest/multinest_src/LICENCE
    - cosmosis/samplers/polychord/polychord_src/LICENCE

  summary: The Cosmological Survey Inference System
  description: |
    CosmoSIS is a framework designed primarily for cosmological
    parameter estimation.
  doc_url: https://cosmosis.readthedocs.io/
  dev_url: https://github.com/joezuntz/cosmosis

extra:
  recipe-maintainers:
    - joezuntz
