{% set name = "cosmosis" %}
{% set version = "0.5.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url:  https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bfab54a67338b2db80017b69ca60728893d8622cfe3933b1dc7539cb0cd35d09

build:
  number: 2
  skip: True  # [(py < 36) or win]
  script:   "{{ PYTHON }} -m pip install . -vv"


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - {{ compiler('cxx') }}
    - make
    - llvm-openmp  # [osx]
    - libgomp      # [linux]    
  host:
    - python
    - pip
    - wheel
    - {{ mpi }}
    - liblapack
    - libblas
    - minuit2_standalone
  run:
    # core
    - python
    - mpi4py
    - matplotlib-base
    - future
    - numpy
    - pip
    - pybind11
    - pyyaml
    - scipy
    - setuptools
    - threadpoolctl
    - git
    # for samplers
    - emcee
    - dynesty
    - minuit2_standalone
    - zeus-mcmc

test:
  imports:
    - cosmosis
  commands:
    - test -f ${SP_DIR}/cosmosis/samplers/multinest/multinest_src/libnest3.so
    - test -f ${SP_DIR}/cosmosis/samplers/multinest/multinest_src/libnest3_mpi.so
    - test -f ${SP_DIR}/cosmosis/samplers/polychord/polychord_src/libchord.so
    - test -f ${SP_DIR}/cosmosis/samplers/polychord/polychord_src/libchord_mpi.so
    - source cosmosis-configure && pytest --pyargs cosmosis
  requires:
    - pytest

about:
  home: https://github.com/joezuntz/cosmosis
  license: BSD-2-Clause AND LicenseRef-non-commerical-use-only
  license_family: BSD
  license_file:
    - LICENSE
    - cosmosis/samplers/multinest/multinest_src/LICENCE
    - cosmosis/samplers/polychord/polychord_src/LICENCE

  summary: The Cosmological Survey Inference System
  description: |
    CosmoSIS is a framework designed primarily for cosmological
    parameter estimation.
  doc_url: https://cosmosis.readthedocs.io/
  dev_url: https://github.com/joezuntz/cosmosis

extra:
  recipe-maintainers:
    - joezuntz
